commands:
  run:
    exec:
      - go run cmd/ca/main.go
    working_dir: .
    description: run ca
  lint:
    exec:
      - staticcheck ./...
    working_dir: .
    description: style check
  build:
    exec:
      - go build -o dist/ca cmd/ca/main.go
    working_dir: .
    description: build ca
