commands:
  run:
    exec:
      - go run cmd/co/main.go
    working_dir: .
    description: run co
  lint:
    exec:
      - staticcheck ./...
      - go vet ./...
    working_dir: .
    description: style check
  build:
    exec:
      - go build -o dist/co cmd/co/main.go
      - shasum -a 256 dist/co
    working_dir: .
    description: build co
  snapshot:
    exec:
      - goreleaser release --snapshot --rm-dist
    working_dir: .
    description: release snapshot
  release:
    exec:
      - git tag -a <args>
      - git push origin <args>
    working_dir: .
    description: release
  echo:
    exec:
      - echo <args>
    description: echo args
  lg:
    exec:
      - ls -l | grep go
    description: list and more
