commands:
  run:
    exec:
      - go run cmd/do/main.go
    working_dir: .
    description: run do
  lint:
    exec:
      - staticcheck ./...
      - go vet ./...
    working_dir: .
    description: style check
  build:
    exec:
      - go build -o dist/do cmd/do/main.go
    working_dir: .
    description: build ca
